Varfolomeev alexander lab4
MrsSbr/group-9 pull request #67
Opened 2022-10-25 05:06 UTC by AlexanderVarfolomeev

2022-11-02 13:22 UTC, AlexanderVarfolomeev commented
Исправил так, что в целом кода меньше стало, надеюсь так станет читабельнее

2022-11-04 20:54 UTC, MrsSbr requested changes

2022-11-06 09:16 UTC, AlexanderVarfolomeev commented on alexander.varfolomeev/lab4/src/Models/LogStatistic.java
> +        return "1xx : " + countOfGeneralCodes.get(0) +
public final List<Integer> countOfGeneralsCode - если заменить это на Map<string, Integer>  то можно будет избавиться от хардкода тут и в getStatisticByAllResources(), правда SortedMap тут все равно останется

2022-11-22 07:41 UTC, MrsSbr approved these changes

2022-11-22 07:41 UTC, merged